### ISSUE TITLE
Correct add support for kernel 6.8

### ISSUE THREAD

**Issue by petrmatula190** [awesometic/realtek-r8152-dkms#22]
Hello, my system76 galp5 got too latest kernel 6.8 and this dkms module must be updated... I try build manually and find correct place. 

r8152.c on line 19687 change function strlcp to strscpy. I try change code only to 

> #if LINUX_VERSION_CODE >= KERNEL_VERSION(6,8,0)    
> strscpy(uinfo->devpath, udev->devpath, sizeof(udev->devpath));    
> #else    
> strlcpy(uinfo->devpath, udev->devpath, sizeof(udev->devpath));    
> #endif /* LINUX_VERSION_CODE >= KERNEL_VERSION(6,8,0) */

After it, I make deb package on ubuntu 22.04.

This update works and i can install module on kernel 6.8 and 6.5 without problem. But if i try install module from running older ekrnele 5.17 or  5.15, i got 

> ERROR (dkms apport): kernel package linux-headers-6.8.0-76060800daily20240311-generic is not supported
> Error! Bad return status for module build on kernel: 6.8.0-76060800daily20240311-generic (x86_64)

Install from running kernel

I try make fork, but I'm not sure if my changes is correct. [URL to fork](https://github.com/petrmatula190/realtek-r8152-dkms)

Please check it and adopt my changes if is correct or make some updates and push it to PPA.

Thanks.

Install log before my code changes was:

> matlala@matlala-galp5 ~ $ sudo apt-get install realtek-r8152-dkms
> Loading package lists… Done
> Building the dependency tree… Done
> Loading status information... Done
> The following NEW packages will be installed:
>    realtek-r8152-dkms
> 0 updated, 1 newly installed, 0 to remove and 10 not updated.
> 0 B/84.0 KB archives must be downloaded.
> After this operation, an additional 706 KB will be used on the disk.
> Selecting the currently unselected package realtek-r8152-dkms.
> (Loading database ... now 586220 files and directories are installed.)
> Preparing to replace …/realtek-r8152-dkms_2.17.1-3~202403030905~ubuntu22.04.1_amd64.deb …
> Unpacking realtek-r8152-dkms (2.17.1-3~202403030905~ubuntu22.04.1) …
> Setting up realtek-r8152-dkms package (2.17.1-3~202403030905~ubuntu22.04.1) …
> Loading new realtek-r8152-2.17.1 DKMS files...
> Building for 6.8.0-76060800daily20240311-generic
> Building for architecture x86_64
> Building initial module for 6.8.0-76060800daily20240311-generic
> ERROR (dkms apport): kernel package linux-headers-6.8.0-76060800daily20240311-generic is not supported
> Error! Bad return status for module build on kernel: 6.8.0-76060800daily20240311-generic (x86_64)
> Consult /var/lib/dkms/realtek-r8152/2.17.1/build/make.log for more information.
> dpkg: error processing package realtek-r8152-dkms (--configure):
>   thread script from installed package realtek-r8152-dkms: post-installation returned error return status 10
> Errors occurred during processing:
>   realtek-r8152-dkms
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> matlala@matlala-galp5 ~ $ cat /var/lib/dkms/realtek-r8152/2.17.1/build/make.log
> DKMS make.log for realtek-r8152-2.17.1 for kernel 6.8.0-76060800daily20240311-generic (x86_64)
> Thu Apr 04 2024 17:06:33 CEST
> make -C src/ modules
> make[1]: Entering directory "/var/lib/dkms/realtek-r8152/2.17.1/build/src"
> make -C /lib/modules/6.8.0-76060800daily20240311-generic/build M=/var/lib/dkms/realtek-r8152/2.17.1/build/src modules
> make[2]: Entering directory "/usr/src/linux-headers-6.8.0-76060800daily20240311-generic"
> warning: the compiler differs from the one used to build the kernel
>    The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
>    You are using: gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
>    CC [M] /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152.o
> /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152.c: In function 'rtltool_ioctl':
> /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152.c:19687:17: error: implicit declaration of function 'strlcpy'; did you mean 'strscpy'? [-Werror=implicit-function-declaration]
> 19687 | strlcpy(uinfo->devpath, udev->devpath, sizeof(udev->devpath));
>        | ^~~~~~~
>        | strscpy
> /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152.c: At top level:
> /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152.c:20209:4: warning: no previous prototype for 'rtl8152_get_version' [-Wmissing-prototypes]
> 20209 | u8 rtl8152_get_version(struct usb_interface *intf)
>        | ^~~~~~~~~~~~~~~~~~~
> cc1: some warnings being treated as errors
> make[4]: *** [scripts/Makefile.build:243: /var/lib/dkms/realtek-r8152/2.17.1/build/src/r8152.o] Error 1
> make[3]: *** [/usr/src/linux-headers-6.8.0-76060800daily20240311-generic/Makefile:1927: /var/lib/dkms/realtek-r8152/2.17.1/build/src] Error 2
> make[2]: *** [Makefile:240: __sub-make] Error 2
> make[2]: Leaving directory "/usr/src/linux-headers-6.8.0-76060800daily20240311-generic"
> make[1]: *** [Makefile:24: modules] Error 2
> make[1]: Leaving directory "/var/lib/dkms/realtek-r8152/2.17.1/build/src"
> make: *** [Makefile:18: modules] Error 2

**Comment by awesometic** [comment]
Hello,

Sorry for my too-late reply 😅 
I think it should be fine, `strlcpy` is deprecated in kernel 6.8 and we can easily find it on the Internet that the developers fixed this issues by replacing `strlcpy` with `strscpy` like you.
In fact, `strscpy` does the same thing as `strlcpy` does, but it is safer since it doesn't truncate the source string if it exceeds the size while `strlcpy` truncates it silently.
So, you did it correctly.

As of 2.18.1 driver, it seems Realtek replaces all the `strlcpy` usage with `strscpy`. They did so many changes on this version compared to the previous one and it looks like they decided to use the safer function.

You did a great job and helped people suffering from installing it on kernel 6.8.
As the issue is resolved, I will close this issue.
And I also close the PR #20, which has the same correction in the contents.

Thank you. 😃

**Comment by petrmatula190** [comment]
Hi, time is not problem :-) Usually, I can find and compole myself. 

In this long time, i upgraded to ubuntu 24.04 (with oem ekrnel 6.8.0) and removed this driver, everything seems works fine :-)

So, I will try your new version again :-)
