### ISSUE TITLE
7.0.2 build problem

### ISSUE THREAD

**Issue by jauling** [awesometic/realtek-r8152-dkms#39]
Running Proxmox on Debian 13. 
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 13 (trixie)
Release:	13
Codename:	trixie
```

Installed most recent Proxmox Linux kernel 7.0.2-4-pve and headers. Then reinstalled the dkms deb package again.

```
# dpkg -i realtek-r8152-dkms_2.21.4-1_amd64.deb 
(Reading database ... 107085 files and directories currently installed.)
Preparing to unpack realtek-r8152-dkms_2.21.4-1_amd64.deb ...
Module realtek-r8152/2.21.4 for kernel 6.17.13-4-pve (amd64):
Before uninstall, this module version was ACTIVE on this kernel.
Deleting /lib/modules/6.17.13-4-pve/updates/dkms/r8152.ko
Restoring archived original module /lib/modules/6.17.13-4-pve/kernel/drivers/net/usb/r8152.ko
Running depmod... done.

Deleting module realtek-r8152/2.21.4 completely from the DKMS tree.
Unpacking realtek-r8152-dkms (2.21.4-1) over (2.21.4-1) ...
Setting up realtek-r8152-dkms (2.21.4-1) ...
Loading new realtek-r8152/2.21.4 DKMS files...
Building for 7.0.2-4-pve
Building for architecture amd64

Building initial module realtek-r8152/2.21.4 for 7.0.2-4-pve
Sign command: /lib/modules/7.0.2-4-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)....(bad exit status: 2)
Failed command:
'make' -j4 modules KERNELDIR=/lib/modules/7.0.2-4-pve/build

Error! Bad return status for module build on kernel: 7.0.2-4-pve (amd64)
Consult /var/lib/dkms/realtek-r8152/2.21.4/build/make.log for more information.
dpkg: error processing package realtek-r8152-dkms (--install):
 installed realtek-r8152-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 realtek-r8152-dkms
```

```
# cat /var/lib/dkms/realtek-r8152/2.21.4/build/make.log
DKMS (dkms-3.2.2) make.log for realtek-r8152/2.21.4 for kernel 7.0.2-4-pve (amd64)
Mon May 18 10:26:24 PM CEST 2026

Building module(s)
# command: 'make' -j4 modules KERNELDIR=/lib/modules/7.0.2-4-pve/build
make -C src/ modules
make[1]: Entering directory '/var/lib/dkms/realtek-r8152/2.21.4/build/src'
make -C /lib/modules/7.0.2-4-pve/build M=/var/lib/dkms/realtek-r8152/2.21.4/build/src modules
make[2]: Entering directory '/usr/src/linux-headers-7.0.2-4-pve'
make[3]: Entering directory '/var/lib/dkms/realtek-r8152/2.21.4/build/src'
warning: pahole version differs from the one used to build the kernel
  The kernel was built with: 130
  You are using:             0
  CC [M]  r8152.o
r8152.c: In function ‘rtl_mapt_read’:
r8152.c:2176:15: error: implicit declaration of function ‘hex2bin’ [-Wimplicit-function-declaration]
 2176 |         ret = hex2bin(buf, obj->string.pointer + 9, sizeof(buf));
      |               ^~~~~~~
make[5]: *** [/usr/src/linux-headers-7.0.2-4-pve/scripts/Makefile.build:289: r8152.o] Error 1
make[4]: *** [/usr/src/linux-headers-7.0.2-4-pve/Makefile:2110: .] Error 2
make[3]: *** [/usr/src/linux-headers-7.0.2-4-pve/Makefile:248: __sub-make] Error 2
make[3]: Leaving directory '/var/lib/dkms/realtek-r8152/2.21.4/build/src'
make[2]: *** [Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-7.0.2-4-pve'
make[1]: *** [Makefile:32: modules] Error 2
make[1]: Leaving directory '/var/lib/dkms/realtek-r8152/2.21.4/build/src'
make: *** [Makefile:18: modules] Error 2

# exit code: 2
# elapsed time: 00:00:03
----------------------------------------------------------------
```

**Comment by llevet** [comment]
Try install latest version : 

dpkg -i realtek-r8152-dkms_2.21.4-2_amd64.deb

**Comment by jauling** [comment]
Thanks, that did the trick.

```
# dpkg -i realtek-r8152-dkms_2.21.4-2_amd64.deb 
(Reading database ... 98889 files and directories currently installed.)
Preparing to unpack realtek-r8152-dkms_2.21.4-2_amd64.deb ...
Deleting module realtek-r8152/2.21.4 completely from the DKMS tree.
Unpacking realtek-r8152-dkms (2.21.4-2) over (2.21.4-2) ...
Setting up realtek-r8152-dkms (2.21.4-2) ...
Loading new realtek-r8152/2.21.4 DKMS files...
Building for 7.0.2-6-pve
Building for architecture amd64

Building initial module realtek-r8152/2.21.4 for 7.0.2-6-pve
Sign command: /lib/modules/7.0.2-6-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)....... done.
Signing module /var/lib/dkms/realtek-r8152/2.21.4/build/src/r8152.ko
Found pre-existing /lib/modules/7.0.2-6-pve/kernel/drivers/net/usb/r8152.ko, archiving for uninstallation
Installing /lib/modules/7.0.2-6-pve/updates/dkms/r8152.ko
Running depmod.... done.
realtek-r8152-dkms: Installing udev rules to prevent from loading built-in old driver...
realtek-r8152-dkms: Reload udev...
realtek-r8152-dkms: Remove temporary files...
```

Not sure if it's necessary, but I also ran `update-initramfs -u -k all` before I rebooted.
