### ISSUE TITLE
It is possible add support to kernel 6.0 and up?

### ISSUE THREAD

**Issue by petrmatula190** [awesometic/realtek-r8152-dkms#6]
I need use newest kernel than LTS or HWE in Ubuntu (because i Use very new HW and have laptop from system76, this manufacturer recomand and use kernel  6.0 in this driver repository). Realtek decided support max kernel 5.17. 

Linus Tovards have some change in mainline kernel repo, but it's too mutch hardware stuff for my coding knowlenge.
[mainline git repo](https://github.com/torvalds/linux/blob/master/drivers/net/usb/r8152.c)

```
matlala@matlala-galp5 ~/git/realtek-r8152-dkms $ uname -a
Linux matlala-galp5 6.0.6-76060006-generic #202210290932~1669062050~22.04~d94609a~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux

matlala@matlala-galp5 ~/git/realtek-r8152-dkms $sudo ./dkms-install.sh
About to run dkms install steps...
Error! DKMS tree already contains: r8152-2.16.3
You cannot add the same module/version combo more than once.

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
'make' -j8 modules....(bad exit status: 2)
ERROR (dkms apport): binary package for r8152: 2.16.3 not found
Error! Bad return status for module build on kernel: 6.0.6-76060006-generic (x86_64)
Consult /var/lib/dkms/r8152/2.16.3/build/make.log for more information.

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
'make' -j8 modules....(bad exit status: 2)
ERROR (dkms apport): binary package for r8152: 2.16.3 not found
Error! Bad return status for module build on kernel: 6.0.6-76060006-generic (x86_64)
Consult /var/lib/dkms/r8152/2.16.3/build/make.log for more information.
Finished running dkms install steps.
Copy the dedicated udev rules file...
Restarting udev...
Finished.

matlala@matlala-galp5 ~/git/realtek-r8152-dkms $ cat /var/lib/dkms/r8152/2.16.3/build/make.log
DKMS make.log for r8152-2.16.3 for kernel 6.0.6-76060006-generic (x86_64)
Pá 30. prosince 2022, 23:09:42 CET
make -C src/ modules
make[1]: Vstupuje se do adresáře „/var/lib/dkms/r8152/2.16.3/build/src“
make -C /lib/modules/6.0.6-76060006-generic/build M=/var/lib/dkms/r8152/2.16.3/build/src modules
make[2]: Vstupuje se do adresáře „/usr/src/linux-headers-6.0.6-76060006-generic“
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  CC [M]  /var/lib/dkms/r8152/2.16.3/build/src/r8152.o
/var/lib/dkms/r8152/2.16.3/build/src/r8152.c: In function ‘sg_en_store’:
/var/lib/dkms/r8152/2.16.3/build/src/r8152.c:20462:9: error: implicit declaration of function ‘netif_set_gso_max_size’; did you mean ‘netif_set_tso_max_size’? [-Werror=implicit-function-declaration]
20462 |         netif_set_gso_max_size(netdev, tso_size);
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         netif_set_tso_max_size
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:249: /var/lib/dkms/r8152/2.16.3/build/src/r8152.o] Chyba 1
make[2]: *** [Makefile:1858: /var/lib/dkms/r8152/2.16.3/build/src] Chyba 2
make[2]: Opouští se adresář „/usr/src/linux-headers-6.0.6-76060006-generic“
make[1]: *** [Makefile:24: modules] Chyba 2
make[1]: Opouští se adresář „/var/lib/dkms/r8152/2.16.3/build/src“
make: *** [Makefile:18: modules] Chyba 2
```

**Comment by petrmatula190** [comment]
I found one working solutions in other repo: https://github.com/wget/realtek-r8152-linux
But not fix for uncoming kernel 6.2

**Comment by awesometic** [comment]
Hi,

I just uploaded the patches to add supporting kernels 5.18, and 6.1 by separate edits.
I fixed this supporting issue in a different way that is more LGTM.
Didn't apply the mainline changes.

For me, it compiles and works flawlessly on my Odroid N2+ which uses kernel 6.0.11.

```
$ sudo dmesg | grep -i r8152
[   93.212988] r8152: loading out-of-tree module taints kernel.
[   93.445590] r8152 2-1.4:1.0 (unnamed net_device) (uninitialized): netif_napi_add_weight() called with weight 256
[   93.461445] r8152 2-1.4:1.0 eth1: v2.16.3 (2022/07/06)
[   93.461459] r8152 2-1.4:1.0 eth1: This product is covered by one or more of the following patents:
[   93.461565] usbcore: registered new interface driver r8152
[  170.919226] r8152 2-1.4:1.0 eth1: carrier on
```

Could you please test the new version 2.16.3-4 on your side?

**Comment by petrmatula190** [comment]
Nice, I tested prepackaged deb on my PC. I have USB A and USB C ethernet cards  from aliexpress (from FENVi manufacturer)... and no problem on kernel 6.0.6 :-)
Nice. I will need test it for more time, but you can add it to your PPA. I prefer use this :-)

**Comment by petrmatula190** [comment]
I update and update again...
But with kernel 6.1.XXX on 7th february, stop working and dmesg shows this:

`[Út úno  7 16:24:41 2023] usb 2-1: USB disconnect, device number 119
[Út úno  7 16:24:41 2023] xhci_hcd 0000:00:0d.0: WARN Set TR Deq Ptr cmd failed due to incorrect slot or ep state.
[Út úno  7 16:24:42 2023] usb 2-1: new SuperSpeed USB device number 120 using xhci_hcd
[Út úno  7 16:24:42 2023] usb 2-1: New USB device found, idVendor=0bda, idProduct=8156, bcdDevice=31.04
[Út úno  7 16:24:42 2023] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=6
[Út úno  7 16:24:42 2023] usb 2-1: Product: USB 10/100/1G/2.5G LAN
[Út úno  7 16:24:42 2023] usb 2-1: Manufacturer: Realtek
[Út úno  7 16:24:42 2023] usb 2-1: SerialNumber: 4013000001
[Út úno  7 16:24:42 2023] cdc_ncm 2-1:2.0: MAC-Address: 1c:bf:ce:fb:e2:62
[Út úno  7 16:24:42 2023] cdc_ncm 2-1:2.0: setting rx_max = 16384
[Út úno  7 16:24:42 2023] cdc_ncm 2-1:2.0: setting tx_max = 16384
[Út úno  7 16:24:42 2023] cdc_ncm 2-1:2.0 eth1: register 'cdc_ncm' at usb-0000:00:0d.0-1, CDC NCM (NO ZLP), 1c:bf:ce:fb:e2:62
[Út úno  7 16:24:42 2023] usb 2-1: USB disconnect, device number 120
[Út úno  7 16:24:47 2023] xhci_hcd 0000:00:0d.0: WARN Set TR Deq Ptr cmd failed due to incorrect slot or ep state.
[Út úno  7 16:24:47 2023] usb 2-1: Disable of device-initiated U1 failed.
[Út úno  7 16:24:47 2023] cdc_ncm 2-1:2.0 eth1: unregister 'cdc_ncm' usb-0000:00:0d.0-1, CDC NCM (NO ZLP)
[Út úno  7 16:24:47 2023] usb 2-1: Device not responding to setup address.
[Út úno  7 16:24:47 2023] usb 2-1: Device not responding to setup address.
[Út úno  7 16:24:48 2023] usb 2-1: device not accepting address 121, error -71
[Út úno  7 16:24:48 2023] usb 2-1: new SuperSpeed USB device number 122 using xhci_hcd
[Út úno  7 16:24:48 2023] usb 2-1: New USB device found, idVendor=0bda, idProduct=8156, bcdDevice=31.04
[Út úno  7 16:24:48 2023] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=6
[Út úno  7 16:24:48 2023] usb 2-1: Product: USB 10/100/1G/2.5G LAN
[Út úno  7 16:24:48 2023] usb 2-1: Manufacturer: Realtek
[Út úno  7 16:24:48 2023] usb 2-1: SerialNumber: 4013000001
[Út úno  7 16:24:48 2023] cdc_ncm 2-1:2.0: MAC-Address: 1c:bf:ce:fb:e2:62
[Út úno  7 16:24:48 2023] cdc_ncm 2-1:2.0: setting rx_max = 16384
[Út úno  7 16:24:48 2023] cdc_ncm 2-1:2.0: setting tx_max = 16384
[Út úno  7 16:24:48 2023] cdc_ncm 2-1:2.0 eth1: register 'cdc_ncm' at usb-0000:00:0d.0-1, CDC NCM (NO ZLP), 1c:bf:ce:fb:e2:62
[Út úno  7 16:24:48 2023] cdc_ncm 2-1:2.0 eth1: unregister 'cdc_ncm' usb-0000:00:0d.0-1, CDC NCM (NO ZLP)
[Út úno  7 16:24:48 2023] usb 2-1: reset SuperSpeed USB device number 122 using xhci_hcd
[Út úno  7 16:24:48 2023] usb 2-1: USB disconnect, device number 122
[Út úno  7 16:24:49 2023] xhci_hcd 0000:00:0d.0: WARN Set TR Deq Ptr cmd failed due to incorrect slot or ep state.
[Út úno  7 16:24:49 2023] r8152 2-1:1.0 (unnamed net_device) (uninitialized): get_registers -110
[Út úno  7 16:24:49 2023] r8152 2-1:1.0 (unnamed net_device) (uninitialized): get_registers -19
[Út úno  7 16:25:00 2023] r8152 2-1:1.0 eth1: v2.16.3 (2022/07/06)
[Út úno  7 16:25:00 2023] r8152 2-1:1.0 eth1: This product is covered by one or more of the following patents:
                            		US6,570,884, US6,115,776, and US6,327,625.

[Út úno  7 16:25:00 2023] usb 2-1: new SuperSpeed USB device number 123 using xhci_hcd
[Út úno  7 16:25:00 2023] usb 2-1: New USB device found, idVendor=0bda, idProduct=8156, bcdDevice=31.04
[Út úno  7 16:25:00 2023] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=6
[Út úno  7 16:25:00 2023] usb 2-1: Product: USB 10/100/1G/2.5G LAN
[Út úno  7 16:25:00 2023] usb 2-1: Manufacturer: Realtek
[Út úno  7 16:25:00 2023] usb 2-1: SerialNumber: 4013000001
[Út úno  7 16:25:00 2023] cdc_ncm 2-1:2.0: MAC-Address: 1c:bf:ce:fb:e2:62
[Út úno  7 16:25:00 2023] cdc_ncm 2-1:2.0: setting rx_max = 16384
[Út úno  7 16:25:00 2023] cdc_ncm 2-1:2.0: setting tx_max = 16384
[Út úno  7 16:25:00 2023] cdc_ncm 2-1:2.0 eth1: register 'cdc_ncm' at usb-0000:00:0d.0-1, CDC NCM (NO ZLP), 1c:bf:ce:fb:e2:62
[Út úno  7 16:25:00 2023] cdc_ncm 2-1:2.0 eth1: unregister 'cdc_ncm' usb-0000:00:0d.0-1, CDC NCM (NO ZLP)
[Út úno  7 16:25:01 2023] usb 2-1: reset SuperSpeed USB device number 123 using xhci_hcd
[Út úno  7 16:25:01 2023] r8152 2-1:1.0 eth1: v2.16.3 (2022/07/06)
[Út úno  7 16:25:01 2023] r8152 2-1:1.0 eth1: This product is covered by one or more of the following patents:
                            		US6,570,884, US6,115,776, and US6,327,625.`


On last week, system76 update your repos and add kernel 6.2, still not working.

`[Út bře 14 23:32:10 2023] usb 4-4.4: new SuperSpeed USB device number 7 using xhci_hcd
[Út bře 14 23:32:10 2023] usb 4-4.4: New USB device found, idVendor=0bda, idProduct=8156, bcdDevice=31.04
[Út bře 14 23:32:10 2023] usb 4-4.4: New USB device strings: Mfr=1, Product=2, SerialNumber=6
[Út bře 14 23:32:10 2023] usb 4-4.4: Product: USB 10/100/1G/2.5G LAN
[Út bře 14 23:32:10 2023] usb 4-4.4: Manufacturer: Realtek
[Út bře 14 23:32:10 2023] usb 4-4.4: SerialNumber: 4013000001
[Út bře 14 23:32:10 2023] cdc_ncm 4-4.4:2.0: MAC-Address: 1c:bf:ce:fb:e2:62
[Út bře 14 23:32:10 2023] cdc_ncm 4-4.4:2.0: setting rx_max = 16384
[Út bře 14 23:32:10 2023] cdc_ncm 4-4.4:2.0: setting tx_max = 16384
[Út bře 14 23:32:10 2023] cdc_ncm 4-4.4:2.0 eth1: register 'cdc_ncm' at usb-0000:00:14.0-4.4, CDC NCM (NO ZLP), 1c:bf:ce:fb:e2:62
[Út bře 14 23:32:10 2023] cdc_ncm 4-4.4:2.0 eth1: unregister 'cdc_ncm' usb-0000:00:14.0-4.4, CDC NCM (NO ZLP)
[Út bře 14 23:32:10 2023] r8152: disagrees about version of symbol module_layout
[Út bře 14 23:32:10 2023] r8152: disagrees about version of symbol module_layout
[Út bře 14 23:32:11 2023] r8169 0000:25:00.0 eth0: Link is Down
matlala@matlala-galp5 ~ $ uname -a
Linux matlala-galp5 6.2.0-76060200-generic #202302191831~1678319661~22.04~4d98339~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux

[Út úno  7 16:25:04 2023] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[Út úno  7 16:25:04 2023] r8152 2-1:1.0 eth1: carrier on`

Do you know, how to fix it? This USB  card working around until to end of January 2023, after it have not connected it for some time and from 7th February, not working again and I still use integrated 1G ethernet in my, laptop, because i had not time post this issue.

**Comment by nikitosiusis** [comment]
```r8152: disagrees about version of symbol module_layout``` typically means that your kernel module was compiled not for this kernel
try from the very beginning
remove all packages about realtek
clean /var/lib/dkms directory from all realtek driver modules
start over from fresh git version

it works fine for me with 6.2.10

**Comment by awesometic** [comment]
DKMS should rebuild the module when you update the kernel, but if it doesn't you can try the following methods.

1. Use `dkms build` command. You can specify the module name and the version by `dkms status`
2. Remove all the related packages, which may also remove the things, and install the PPA version again.

**Comment by petrmatula190** [comment]
Thanks for small advise guys :-) It's true... I reinstall driver and recompile  dkms modules and all working again. I will must give more attention while update dmks :-)
